-- MySQL Script generated by MySQL Workbench
-- Fri Jul  7 15:06:46 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bachometro
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bachometro
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bachometro` DEFAULT CHARACTER SET utf8 ;
USE `bachometro` ;

-- -----------------------------------------------------
-- Table `bachometro`.`Usuario_datos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bachometro`.`Usuario_datos` (
  `Id_usuario_datos` INT NOT NULL AUTO_INCREMENT,
  `Apellido_paterno` VARCHAR(45) NOT NULL,
  `Apellido_materno` VARCHAR(45) NOT NULL,
  `Nombres` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_usuario_datos`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bachometro`.`Brigadas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bachometro`.`Brigadas` (
  `Id_brigada` INT NOT NULL,
  `Nombre_brigada` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Id_brigada`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bachometro`.`Usuarios`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bachometro`.`Usuarios` (
  `Id_usuario` INT NOT NULL AUTO_INCREMENT,
  `Usuario` VARCHAR(25) NOT NULL,
  `Contrasena` VARCHAR(255) NOT NULL,
  `Correo` VARCHAR(45) NOT NULL,
  `Tipo_usuario` TINYINT(1) NOT NULL,
  `Encargado` TINYINT NULL,
  `Id_usuario_datos` INT NOT NULL,
  `Id_brigada` INT NULL,
  PRIMARY KEY (`Id_usuario`, `Id_usuario_datos`),
  UNIQUE INDEX `Usuario_UNIQUE` (`Usuario` ASC),
  INDEX `fk_Usuarios_Usuario_datos_idx` (`Id_usuario_datos` ASC),
  INDEX `fk_Usuarios_Brigadas1_idx` (`Id_brigada` ASC),
  UNIQUE INDEX `Correo_UNIQUE` (`Correo` ASC),
  CONSTRAINT `fk_Usuarios_Usuario_datos`
    FOREIGN KEY (`Id_usuario_datos`)
    REFERENCES `bachometro`.`Usuario_datos` (`Id_usuario_datos`)
    ON DELETE RESTRICT
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuarios_Brigadas1`
    FOREIGN KEY (`Id_brigada`)
    REFERENCES `bachometro`.`Brigadas` (`Id_brigada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bachometro`.`Reportes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bachometro`.`Reportes` (
  `Id_reporte` INT NOT NULL AUTO_INCREMENT,
  `Fecha` DATE NOT NULL,
  `Latitud` VARCHAR(45) NOT NULL,
  `Longitud` VARCHAR(45) NOT NULL,
  `Referencia` VARCHAR(100) NULL,
  `Comentario` VARCHAR(255) NULL,
  `Imagen` VARCHAR(100) NULL,
  `Id_usuario` INT NOT NULL,
  `Id_brigada` INT NULL,
  PRIMARY KEY (`Id_reporte`, `Id_usuario`),
  INDEX `fk_Reportes_Usuarios1_idx` (`Id_usuario` ASC),
  INDEX `fk_Reportes_Brigadas1_idx` (`Id_brigada` ASC),
  CONSTRAINT `fk_Reportes_Usuarios1`
    FOREIGN KEY (`Id_usuario`)
    REFERENCES `bachometro`.`Usuarios` (`Id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Reportes_Brigadas1`
    FOREIGN KEY (`Id_brigada`)
    REFERENCES `bachometro`.`Brigadas` (`Id_brigada`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bachometro`.`Reporte_historial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bachometro`.`Reporte_historial` (
  `Id_reporte_historial` INT NOT NULL AUTO_INCREMENT,
  `Descripcion` VARCHAR(255) NULL,
  `Fecha` DATE NOT NULL,
  `Estatus` SET('En espera', 'Atendido', 'Finalizado', 'Cancelado') NOT NULL DEFAULT 'En espera',
  `Id_reporte` INT NOT NULL,
  PRIMARY KEY (`Id_reporte_historial`, `Id_reporte`),
  INDEX `fk_Reporte_historial_Reportes1_idx` (`Id_reporte` ASC),
  CONSTRAINT `fk_Reporte_historial_Reportes1`
    FOREIGN KEY (`Id_reporte`)
    REFERENCES `bachometro`.`Reportes` (`Id_reporte`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
